/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(examples)'}/TabScreen` | `/TabScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(examples)'}/storyui` | `/storyui`; params?: Router.UnknownInputParams; } | { pathname: `${'/(examples)'}/swiper` | `/swiper`; params?: Router.UnknownInputParams; } | { pathname: `${'/(examples)'}/themeswitcher` | `/themeswitcher`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(examples)'}/TabScreen` | `/TabScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(examples)'}/storyui` | `/storyui`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(examples)'}/swiper` | `/swiper`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(examples)'}/themeswitcher` | `/themeswitcher`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(examples)'}/TabScreen${`?${string}` | `#${string}` | ''}` | `/TabScreen${`?${string}` | `#${string}` | ''}` | `${'/(examples)'}/storyui${`?${string}` | `#${string}` | ''}` | `/storyui${`?${string}` | `#${string}` | ''}` | `${'/(examples)'}/swiper${`?${string}` | `#${string}` | ''}` | `/swiper${`?${string}` | `#${string}` | ''}` | `${'/(examples)'}/themeswitcher${`?${string}` | `#${string}` | ''}` | `/themeswitcher${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(examples)'}/TabScreen` | `/TabScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(examples)'}/storyui` | `/storyui`; params?: Router.UnknownInputParams; } | { pathname: `${'/(examples)'}/swiper` | `/swiper`; params?: Router.UnknownInputParams; } | { pathname: `${'/(examples)'}/themeswitcher` | `/themeswitcher`; params?: Router.UnknownInputParams; };
    }
  }
}
